### ISSUE TITLE
Breaking change in BlackDuck API - limit attribute of rest endpoints has changed

### ISSUE THREAD

**Issue by Datenberg** [blackducksoftware/bd_export_spdx2.2#11]
Hey there, 

the SPDX exporter has a conflict with BlackDuck version update v2022.2.0 due to a change in the API: the limit attribute of rest endpoints has changed. Curently the exporter has set a limit of 5000, which is hard-coded at several positions (projects.py, process.py, data.py. The current version is not compatible with 5000, it is possible to use 1000, otherwise you get an error. 

regards

David Schumm [david.schumm@mercedes-benz.com](mailto:david.schumm@mercedes-benz.com) on behalf of Daimler TSS GmbH.

[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by epienaarIDBS** [comment]
Could we remove the limit all together?

**Comment by matthewb66** [comment]
Updated to version 0.24 to address the API limits introduced in Black Duck v2022.2
Also implemented a new option to replace specific JSON output fields with supplied values.
