### ISSUE TITLE
CPE in BOM exported from BlackDuck

### ISSUE THREAD

**Issue by chinmaybhave05** [blackducksoftware/bd_export_spdx2.2#12]
I used this tool to generate BOM from Black Duck in SPDX 2.2 and could not find CPEs included in the BOM. How can I export a BOM which includes CPEs in it?

**Comment by matthewb66** [comment]
CPEs are not a mandated part of the SBOM standard because it is planned to be replaced (not being fit for purpose).
PURL is used as the required component identifier as defines in the SBOM standard.
