### ISSUE TITLE
SPDX export not conforming to SPDX specification

### ISSUE THREAD

**Issue by melba-lopez** [blackducksoftware/bd_export_spdx2.2#15]
Hi Folks!

I've been given an SBOM from blackduck and attempted to load it into depedency track.  Depedency track accepted it but could not do anything with it.  Further investigation revealed that the spdx output does not properly conform to spdx specifications and gives the following messages repeated over 1000x per package:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/101211710/173106869-902ff3f3-40d8-463b-b232-84f096b1556b.png">

`The following warning(s) were raised: [object instance has properties which are not allowed by the schema: ["copyrightText","downloadLocation","externalRefs","filesAnalyzed"] for {"pointer":""}, object instance has properties which are not allowed by the schema: ["licenseID"] for {"pointer":"/hasExtractedLicensingInfos/0"}`

`object instance has properties which are not allowed by the schema: ["packageComment"] for {"pointer":"/packages/0"}, object instance has properties which are not allowed by the schema: ["packageComment","packageHomepage","packageSupplier"] for {"pointer":"/packages/1"},`

`Invalid license id '__anon__5'. Must start with 'LicenseRef-' and made up of the characters from the set 'a'-'z', 'A'-'Z', '0'-'9', '+', '_', '.', and '-'.`

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks

**Comment by melba-lopez** [comment]
hi @matthewb66 thanks for the update.  Unfortunately our customer provided output to us by using this script.  I opened this ticket hoping to bring awareness to the team.
