### ISSUE TITLE
Issue with aiohttp ClientSession not working with cluster proxy

### ISSUE THREAD

**Issue by MicDeDuiwel** [blackducksoftware/bd_export_spdx2.2#16]
https://github.com/blackducksoftware/bd_export_spdx2.2/blob/1692f1da3b81978a6f95ea1e5462c836eba7a34b/export_spdx/process.py#L356

We have issues runnig bd_export within our cluster and automated pipelines due to proxy issues, we have found that setting the client Sesision to trust the environment works in resolving this issue

`async with ClientSession(trust_env=True) as session:`

Is it possible to add this change?

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks
