### ISSUE TITLE
Misleading error message when project version not found

### ISSUE THREAD

**Issue by Datenberg** [blackducksoftware/bd_export_spdx2.2#17]
Hey there, 

this issue relates to lines 22 ff. in https://github.com/blackducksoftware/bd_export_spdx2.2/blob/master/export_spdx/projects.py

The exporter is giving a misleading error message if a project _version_ is not found, e.g. due to a typo in the version parameter. Error message then states that the project does not exist, although project exists and is correct. Instead the message should note that the version is not found.

regards,

David Schumm [david.schumm@mercedes-benz.com](mailto:david.schumm@mercedes-benz.com) on behalf of Mercedes-Benz Tech Innovation GmbH.

[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks

**Comment by Datenberg** [comment]
There are open pull requests
