### ISSUE TITLE
Exception information is stripped from license Id

### ISSUE THREAD

**Issue by rototof** [blackducksoftware/bd_export_spdx2.2#19]
LicenseIDs with exceptions are deprecated and to be replaced using the WITH operator (https://spdx.org/licenses/exceptions-index.html).

This script however simply strips the exception information (./blob/master/export_spdx/spdx.py)

Example:
'GPL-2.0-with-classpath-exception' will turn to 'GPL-2.0-only'

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks
