### ISSUE TITLE
Enable Proxy support

### ISSUE THREAD

**Issue by Waschndolos** [blackducksoftware/bd_export_spdx2.2#22]
When using this script it's not possible (or at least I didn't manage it) to run it behind a corparate proxy. I think the reason for this is that for example in process.py the "session.get()" is called. This doesn't pick up any environment variables such as http_proxy or https_proxy or no_proxy (or all in capital letters :)). 
Your Blackduck Client object seems to work with these variables. It may be possible to convert the session.get() with the Blackduck Client calls? Or otherwise provide a parameter such like -http_proxy=xxx? 

Would be great to have this feature - otherwise it's hard for us to use this script. Unfortunately I cannot provide a patch since my python skills are on noob level - but I guess you know what I mean?

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks
