### ISSUE TITLE
externalRefs point to Blackduck origin urls

### ISSUE THREAD

**Issue by fbiehl** [blackducksoftware/bd_export_spdx2.2#5]
Hello,

Each package element in the generated SPDX document contains 'externalRefs' array field which ports two reference locators exposing full URL to Blackduck api used. This shows up for reference types BlackDuckHub-Component and BlackDuckHub-Component-Version.

Is this really required to be there?
Any chances to suppress this information?

Thanks

**Comment by fbiehl** [comment]
Example extract:
`{
    "SPDXID": "SPDXRef-Package-ApacheCommonsLang-26",
    "description": "NOASSERTION",
    "downloadLocation": "NOASSERTION",
    "externalRefs": [
        {
            "referenceCategory": "PACKAGE_MANAGER",
            "referenceLocator": "pkg:maven/commons-lang/commons-lang@2.6",
            "referenceType": "purl"
        },
        {
            "referenceCategory": "OTHER",
            "referenceLocator": "https://your-blackduck/api/components/component-id",
            "referenceType": "BlackDuckHub-Component"
        },
        {
            "referenceCategory": "OTHER",
            "referenceLocator": "https://your-blackduck/api/components/component-id/versions/version-id",
            "referenceType": "BlackDuckHub-Component-Version"
        }
    ]
}`

Not sure how useful or needed are those reference locators.
Note that references to Blackduck instance API is also displayed as part of **documentNamespace** field.

**Comment by matthewb66** [comment]
The SPDX standard requires valid URLs for the tool which generates the SPDX file.
What else should be used here?

**Comment by fbiehl** [comment]
If really required, perhaps refer generically to something public ? e.g https://www.blackducksoftware.com/
