### ISSUE TITLE
Export of Usage Information to SPDX planned?

### ISSUE THREAD

**Issue by Datenberg** [blackducksoftware/bd_export_spdx2.2#6]
Hey there, 

within Black Duck there is "Usage Information" shown for components of an SBOM, distinguishing them into Dynamically Linked / Statically Linked etc.; This Usage Information is currently not included in the SPDX export. Browsing through the SPDX spec it seems this information can be reflected in relationships (see https://spdx.github.io/spdx-spec/relationships-between-SPDX-elements/). Are there any plans to extend the SPDX Exporter to also cover the Usage Information?

Regards

David Schumm [david.schumm@mercedes-benz.com](mailto:david.schumm@mercedes-benz.com) on behalf of Daimler TSS GmbH.

[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by matthewb66** [comment]
The SPDX relationship field provides a wide range of options for the types of relationship, but these are heterogeneous covering both the hierarchical relationship (dependency/contains) and usage (static or dynamic linkage).

Given that Black Duck does not identify the actual usage from scanning, with a default of Dynamically Linked, but that all components do have a project relationship (dependency of, contains etc.), it is not sensible to replace all relationships with the usage value by default.

The script is provided as OSS with the option for cloning/forking to support nuanced use-cases, and in this case I would suggest this option if there is something specific required.
