### ISSUE TITLE
Export of custom/non-SPDX license texts

### ISSUE THREAD

**Issue by Datenberg** [blackducksoftware/bd_export_spdx2.2#7]
Hey there, 

is there a way to also export the license texts of the licenses associated with the components in the SPDX? In particular this refers to custom/non-SPDX license texts. Also license texts which have been modified compared to the template are relevant, e.g. an MIT with replaced placeholders. In the export I currently get a corresponding LicenseRef, but no extracted license texts. Is this somehow possible or planned to be added in future?

Thanks and regards

David Schumm [david.schumm@mercedes-benz.com](mailto:david.schumm@mercedes-benz.com) on behalf of Daimler TSS GmbH.

[Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md)

**Comment by matthewb66** [comment]
Custom license text should be exported by default (see line 520 of process.py).
Licenses reported as SPDX standards are not exported with full license text currently.
If the script is not exporting custom license text then please raise a separate issue.
